### ISSUE TITLE
Display the Unit Test Result like in Azure Devops

### ISSUE THREAD

**Issue by fboucher** [FBoucher/ProjectDover#24]
In Azure DevOps we can publish the Unit test results in a chart.
Using the task
```
- task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testRunner: VSTest
        testResultsFiles: '**/*.trx'
      displayName: 'Publish Test Results'
```
And the output look like this. 
![image](https://app.gitkraken.com/api/glo/boards/5da085b3401a08000f7c3b13/attachments/5e344be8757b7a001129a96f)

Is it possible with GitHub Actions
